###  Array Creation and Manipulation

In [ ]:
   banking_data=np.array([
    [1,10346,696,89,6],
    [2,1356,543,67,8],
    [3,53145,685,46,7],
    [4,85774,466,35,6],
    [5,67865,535,64,3],
    [6,32645,636,96,6],
    [7,78547,564,57,7],
    [8,64477,553,73,7],
    [9,26754,867,67,2],
    [10,56843,466,47,5]
])

#1 Create a 4x4 identity matrix using np.eye()
import numpy as np
a=np.eye(4)
a

In [2]:
#2: Create an array of 8 zeros using np.zeros()
import numpy as np
a=np.zeros(8)
a

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#3: Create an array of 6 ones using np.ones()
import numpy as np
a=np.ones(6)
a

array([1., 1., 1., 1., 1., 1.])

In [4]:
#4: Create an array with values from 0 to 15 using np.arange()
import numpy as np
a=np.arange(0 ,16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
#.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
import numpy as np
a=np.linspace(0,100,8)

a

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

### Array Attributes and Information

In [ ]:
#Q2.1: What is the shape of the banking_data array?
banking_data=np.array([
    [1,10346,696,89,5],
    [2,1356,543,67,8],
    [3,53145,685,46,7],
    [4,85774,466,35,6],
    [5,67865,535,64,3],
    [6,32645,636,96,6],
    [7,78547,564,57,7],
    [8,64477,553,73,7],
    [9,26754,867,67,2],
    [10,56843,466,47,5]
])
banking_data.shape

(10, 5)

In [23]:
#Q2.2: What is the data type of the banking_data array?
banking_data.dtype

dtype('float64')

In [47]:
#Q2.3: What is the size (total number of elements) of the banking_data array?
import numpy as np
banking_data=np.array([
    [1,10346,696,89,5],
    [2,1356,543,67,8],
    [3,53145,685,46,7],
    [4,85774,466,35,6],
    [5,67865,535,64,3],
    [6,32645,636,96,6],
    [7,78547,564,57,7],
    [8,64477,553,73,7],
    [9,26754,867,67,2],
    [10,56843,466,47,5]
])
print(banking_data.size)

50


In [48]:
#Q2.4: What is the number of dimensions of the banking_data array?
banking_data=np.array([
    [1,10346,696,89,5],
    [2,1356,543,67,8],
    [3,53145,685,46,7],
    [4,85774,466,35,6],
    [5,67865,535,64,3],
    [6,32645,636,96,6],
    [7,78547,564,57,7],
    [8,64477,553,73,7],
    [9,26754,867,67,2],
    [10,56843,466,47,5]
])
banking_data.ndim

2

In [49]:
#Q2.5: What is the memory size of the banking_data array in bytes?
banking_data.nbytes

400

## Question 3: Indexing and Slicing

In [50]:
#Q3.1: Extract the first row of banking_data
banking_data[0]

array([    1, 10346,   696,    89,     5])

In [51]:
#Q3.2: Extract the last row of banking_data
banking_data[-1]

array([   10, 56843,   466,    47,     5])

In [16]:
#Q3.3: Extract the Account_Balance column (column index 1)
banking_data[1]

array([   2, 1356,  543,   67,    8])

In [52]:
#Q3.4: Extract the first 4 rows and first 3 columns
banking_data[:4,:3]

array([[    1, 10346,   696],
       [    2,  1356,   543],
       [    3, 53145,   685],
       [    4, 85774,   466]])

In [53]:
#Q3.5: Extract rows 3 to 7 (inclusive)
banking_data[3:8]

array([[    4, 85774,   466,    35,     6],
       [    5, 67865,   535,    64,     3],
       [    6, 32645,   636,    96,     6],
       [    7, 78547,   564,    57,     7],
       [    8, 64477,   553,    73,     7]])

### Question 4: Mathematical Operations

In [54]:
#Q4.1: Calculate the sum of all account balances
import numpy as np
a=banking_data[:,1].sum()
print(a)

477752


In [55]:
#Q4.2: Calculate the mean account balance
a = banking_data[:,1].mean()
print(total)

54994.0


In [56]:
#Q4.3: Calculate the standard deviation of account balances
a = banking_data[:, 1].std()
print(a)

27223.01114057738


In [57]:
#Q4.4: Calculate the variance of account balances
a = banking_data[:,1].var()
print(a)

741092335.5600001


In [58]:
#Q4.5: Calculate the median account balance
a = banking_data[:, 1]
total = np.median(a)
print(total)

54994.0



### Question 5: Statistical Functions

In [59]:
#Q5.1: Find the minimum and maximum account balances
a=banking_data[:,1]
print(a.min())
print(a.max())

1356
85774


In [60]:
#Q5.2: Find the minimum and maximum credit scores
a=banking_data[:,2]
print(a.min())
print(a.max())

466
867


In [61]:
#Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
a=banking_data[:,1]
p25=np.percentile(a,25)
p50=np.percentile(a,50)
p75=np.percentile(a,75)
print(p25)
print(p50)
print(p75)

28226.75
54994.0
67018.0


In [62]:
#Q5.4: Calculate the correlation between account balance and credit score
a=banking_data[:,1]
c=banking_data[:,2]
np.corrcoef(a,c)

array([[ 1.        , -0.50900231],
       [-0.50900231,  1.        ]])

In [63]:
#Q5.5: Calculate the covariance between account balance and credit score
a=banking_data[:,1]
c=banking_data[:,2]
np.cov(a,c)

array([[ 8.23435928e+08, -1.79486158e+06],
       [-1.79486158e+06,  1.51005444e+04]])

### Array Reshaping and Manipulation

In [64]:
#Q6.1: Reshape the banking_data to 5 rows × 10 columns
import numpy as np
banking_data = np.array([
     [1,10346,696,89,6],
    [2,1356,543,67,8],
    [3,53145,685,46,7],
    [4,85774,466,35,6],
    [5,67865,535,64,3],
    [6,32645,636,96,6],
    [7,78547,564,57,7],
    [8,64477,553,73,7],
    [9,26754,867,67,2],
    [10,56843,466,47,5]
    
])
reshaped=banking_data.reshape(5,10)
print(reshaped)

[[    1 10346   696    89     6     2  1356   543    67     8]
 [    3 53145   685    46     7     4 85774   466    35     6]
 [    5 67865   535    64     3     6 32645   636    96     6]
 [    7 78547   564    57     7     8 64477   553    73     7]
 [    9 26754   867    67     2    10 56843   466    47     5]]


In [65]:
#Q6.2: Flatten the banking_data to a 1D array
banking_data.flatten()

array([    1, 10346,   696,    89,     6,     2,  1356,   543,    67,
           8,     3, 53145,   685,    46,     7,     4, 85774,   466,
          35,     6,     5, 67865,   535,    64,     3,     6, 32645,
         636,    96,     6,     7, 78547,   564,    57,     7,     8,
       64477,   553,    73,     7,     9, 26754,   867,    67,     2,
          10, 56843,   466,    47,     5])

In [66]:
#Q6.3: _Transpose the banking_data
banking_data.transpose()

array([[    1,     2,     3,     4,     5,     6,     7,     8,     9,
           10],
       [10346,  1356, 53145, 85774, 67865, 32645, 78547, 64477, 26754,
        56843],
       [  696,   543,   685,   466,   535,   636,   564,   553,   867,
          466],
       [   89,    67,    46,    35,    64,    96,    57,    73,    67,
           47],
       [    6,     8,     7,     6,     3,     6,     7,     7,     2,
            5]])

In [67]:
#Q6.4: Split the banking_data into 2 equal parts vertically
np.vsplit(banking_data,2)

[array([[    1, 10346,   696,    89,     6],
        [    2,  1356,   543,    67,     8],
        [    3, 53145,   685,    46,     7],
        [    4, 85774,   466,    35,     6],
        [    5, 67865,   535,    64,     3]]),
 array([[    6, 32645,   636,    96,     6],
        [    7, 78547,   564,    57,     7],
        [    8, 64477,   553,    73,     7],
        [    9, 26754,   867,    67,     2],
        [   10, 56843,   466,    47,     5]])]

In [68]:
#Q6.5: Split the banking_data into 2 equal parts horizontally
banking_data=np.array([
    [1,10346,696,89,6,57],
    [2,1356,543,67,8,90],
    [3,53145,685,46,7,53],
    [4,85774,466,35,6,21],
    [5,67865,535,64,3,98],
    [6,32645,636,96,6,35],
    [7,78547,564,57,7,89],
    [8,64477,553,73,7,54],
    [9,26754,867,67,2,45],
    [10,56843,466,47,5,98]
])
np.hsplit(banking_data,2)

[array([[    1, 10346,   696],
        [    2,  1356,   543],
        [    3, 53145,   685],
        [    4, 85774,   466],
        [    5, 67865,   535],
        [    6, 32645,   636],
        [    7, 78547,   564],
        [    8, 64477,   553],
        [    9, 26754,   867],
        [   10, 56843,   466]]),
 array([[89,  6, 57],
        [67,  8, 90],
        [46,  7, 53],
        [35,  6, 21],
        [64,  3, 98],
        [96,  6, 35],
        [57,  7, 89],
        [73,  7, 54],
        [67,  2, 45],
        [47,  5, 98]])]

### Question 7: Logical Operations and Filtering

In [69]:
#Q7.1: Find customers with account balance greater than $10
bal=banking_data[:,1]>10000
bal

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [70]:
#Q7.2: Find customers with credit score greater than 800
banking_data[:,2]>800

array([False, False, False, False, False, False, False, False,  True,
       False])

In [75]:
#Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
banking_data[(banking_data[:, 3] > 50) & (banking_data[:, 2] < 750)]

array([[    1, 10346,   696,    89,     6,    57],
       [    2,  1356,   543,    67,     8,    90],
       [    5, 67865,   535,    64,     3,    98],
       [    6, 32645,   636,    96,     6,    35],
       [    7, 78547,   564,    57,     7,    89],
       [    8, 64477,   553,    73,     7,    54]])

In [76]:
#Q7.4: Count how many customers have account balance between $10,000 and $100,000
np.sum((banking_data[:,1]=>10000) & (banking_data[:,1]<=100000))

np.int64(9)

In [78]:
#Q7.5: Find the index of the customer with the highest credit score
np.argmax(banking_data[:, 2])

np.int64(8)

### Sorting and Searching

In [84]:
#Q8.1: Sort the banking_data by account balance (ascending)
banking_data[banking_data[:,1].argsort()]


array([[    2,  1356,   543,    67,     8,    90],
       [    1, 10346,   696,    89,     6,    57],
       [    9, 26754,   867,    67,     2,    45],
       [    6, 32645,   636,    96,     6,    35],
       [    3, 53145,   685,    46,     7,    53],
       [   10, 56843,   466,    47,     5,    98],
       [    8, 64477,   553,    73,     7,    54],
       [    5, 67865,   535,    64,     3,    98],
       [    7, 78547,   564,    57,     7,    89],
       [    4, 85774,   466,    35,     6,    21]])

In [85]:
#Q8.2: Sort the banking_data by credit score (descending)
banking_data[ np.argsort(banking_data[:,3])[::-1]]

array([[    6, 32645,   636,    96,     6,    35],
       [    1, 10346,   696,    89,     6,    57],
       [    8, 64477,   553,    73,     7,    54],
       [    9, 26754,   867,    67,     2,    45],
       [    2,  1356,   543,    67,     8,    90],
       [    5, 67865,   535,    64,     3,    98],
       [    7, 78547,   564,    57,     7,    89],
       [   10, 56843,   466,    47,     5,    98],
       [    3, 53145,   685,    46,     7,    53],
       [    4, 85774,   466,    35,     6,    21]])

In [89]:
#Q8.3: Find the indices that would sort the array by years active
np.argsort(banking_data[:,4])

array([8, 4, 9, 0, 5, 3, 6, 2, 7, 1])

In [92]:
#Q8.4: Find the customer with the second highest account balance
bal=banking_data[:,1]
a=np.argsort(bal)[::-1]
num=a[1]
num

np.int64(6)

In [95]:
#Q8.5: Find the customer with the lowest transaction count
sent=banking_data[:,3]
bal=np.argmin(sent)
bal

np.int64(3)

###  Mathematical Functions

In [96]:
#Q9.1: Calculate the absolute values of all elements
np.abs(banking_data)

array([[    1, 10346,   696,    89,     6,    57],
       [    2,  1356,   543,    67,     8,    90],
       [    3, 53145,   685,    46,     7,    53],
       [    4, 85774,   466,    35,     6,    21],
       [    5, 67865,   535,    64,     3,    98],
       [    6, 32645,   636,    96,     6,    35],
       [    7, 78547,   564,    57,     7,    89],
       [    8, 64477,   553,    73,     7,    54],
       [    9, 26754,   867,    67,     2,    45],
       [   10, 56843,   466,    47,     5,    98]])

In [106]:
#Q9.2: Calculate the square root of all account balances
a=banking_data[:,1]
b=np.sqrt(a)
b

array([101.71528892,  36.82390528, 230.53199344, 292.87198569,
       260.50911692, 180.67927385, 280.26237707, 253.92321674,
       163.56650024, 238.41770069])

In [105]:
#Q9.3: Calculate the square of all credit scores
a=banking_data[:,2]
b=np.square(a)
b

array([484416, 294849, 469225, 217156, 286225, 404496, 318096, 305809,
       751689, 217156])

In [3]:
#Q9.4: Calculate the exponential of all transaction countsu.
import numpy as np
banking_data=np.array([
    [1,10346,696,89,6,57],
    [2,1356,543,67,8,90],
    [3,53145,685,46,7,53],
    [4,85774,466,35,6,21],
    [5,67865,535,64,3,98],
    [6,32645,636,96,6,35],
    [7,78547,564,57,7,89],
    [8,64477,553,73,7,54],
    [9,26754,867,67,2,45],
    [10,56843,466,47,5,98]
])
np.exp(banking_data[:,3])

array([4.48961282e+38, 1.25236317e+29, 9.49611942e+19, 1.58601345e+15,
       6.23514908e+27, 4.92345829e+41, 5.68572000e+24, 5.05239363e+31,
       1.25236317e+29, 2.58131289e+20])

In [109]:
#Q9.5: Calculate the natural logarithm of all account balances
a=banking_data[:,1]
b=np.log(a)
b

array([ 9.24435525,  7.21229447, 10.88077931, 11.35947121, 11.12527572,
       10.39344698, 11.27145245, 11.07406385, 10.19443927, 10.94804836])

###  Advanced Operations

In [110]:
 #Q10.1: Calculate the cumulative sum of account balances
a=banking_data[:,1]
b=np.cumsum(a)
b

array([ 10346,  11702,  64847, 150621, 218486, 251131, 329678, 394155,
       420909, 477752])

In [111]:
#Q10.2: Calculate the cumulative product of transaction counts
a=banking_data[:,3]
b=np.cumprod(a)
b

array([                89,               5963,             274298,
                  9600430,          614427520,        58985041920,
            3362147389440,    245436759429120,  16444262881751040,
       772880355442298880])

In [112]:
#Q10.3: Calculate the difference between consecutive account balances
a=banking_data[:,1]
b=np.diff(a)
b

array([ -8990,  51789,  32629, -17909, -35220,  45902, -14070, -37723,
        30089])

In [113]:
#Q10.4: Calculate the gradient of account balances
a=banking_data[:,1]
b=np.gradient(a)
b

array([ -8990. ,  21399.5,  42209. ,   7360. , -26564.5,   5341. ,
        15916. , -25896.5,  -3817. ,  30089. ])

In [116]:
#Q10.5: Calculate the histogram of account balances with 5 bins
a=banking_data[:,1]
b=np.histogram(a,bins=5)
b

(array([2, 2, 0, 4, 2]),
 array([ 1356. , 18239.6, 35123.2, 52006.8, 68890.4, 85774. ]))

###  Random Numbers and Simulation

In [1]:
#Q11.1: Generate 6 random integers between 1 and 1000
import numpy as np
np.random.randint(1,1000,size=6)


array([378, 810, 687, 267, 312,  50], dtype=int32)

In [2]:
#Q11.2: Generate 6 random floats between 0 and 1
np.random.rand(6)

array([0.28851025, 0.25811997, 0.43643388, 0.52869492, 0.65668012,
       0.77731291])

In [ ]:
#Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)


In [2]:
#Q11.4: Shuffle the banking_data rows randomly
import  numpy as np
banking_data=np.array([
    [1,10346,696,89,6],
    [2,1356,543,67,8],
    [3,53145,685,46,7],
    [4,85774,466,35,6],
    [5,67865,535,64,3],
    [6,32645,636,96,6],
    [7,78547,564,57,7],
    [8,64477,553,73,7],
    [9,26754,867,67,2],
    [10,56843,466,47,5]
])
np.random.shuffle(banking_data)

In [ ]:
#Q11.5: Set random seed to 123 and generate 4 random numbers

### Linear Algebra Operations

In [3]:
#Q12.1: Calculate the dot product of account balance and credit score columns
a=banking_data[:,1]
b=banking_data[:,2]
c=np.dot(a,b)
c

np.int64(271022973)

In [5]:
#Q12.2: Calculate the cross product of first two rows
import numpy as np
r1=banking_data[0, :3]
r2=banking_data[1, :3]
np.cross(r1,r2)


array([4674102,     849,  -19336])

In [9]:
#Q12.3: Calculate the norm (magnitude) of the account balance column
import numpy as np
a=banking_data[:, 1]
b=np.linalg.norm(a)
print(b)

173883.92883185035


In [19]:
#Q12.4: Create a 3x3 matrix and calculate its determinant
import numpy as np
matrix = np.array([
    [6, 8, 1],
    [3, 1, 6],
    [1, 2, 3]
])
det = np.linalg.det(matrix)
print(det)


-72.99999999999999


In [20]:
#Q12.5: Calculate the inverse of the 3x3 matrix
np.linalg.inv(matrix)

array([[ 0.12328767,  0.30136986, -0.64383562],
       [ 0.04109589, -0.23287671,  0.45205479],
       [-0.06849315,  0.05479452,  0.24657534]])

### String Operations

In [21]:
#Q13.1: Convert all customer IDs to strings
banking_data = np.array([
    [1,10346,696,89,6],
    [2,1356,543,67,8],
    [3,53145,685,46,7],
    [4,85774,466,35,6],
    [5,67865,535,64,3],
    [6,32645,636,96,6],
    [7,78547,564,57,7],
    [8,64477,553,73,7],
    [9,26754,867,67,2],
    [10,56843,466,47,5]
])
banking_data[:,0].astype(str)

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

In [28]:
#Q13.2: Check if any customer ID contains '100'
import numpy as np
customer_id=banking_data[:,0].astype(str)
np.any(np.char.find(customer_id, '100') != -1)

np.False_

In [ ]:
#Q13.3: Convert all customer IDs to uppercase (if they were strings)

In [30]:
#Q13.4: Count the length of each customer ID string
a=banking_data[:,0].astype(str)
np.char.str_len(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 2])

In [31]:
#Q13.5: Replace '100' with 'CUST' in customer IDs
a=banking_data[:,0].astype(str)
np.char.replace(a,'100','CUST')

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U2')

### Date and Time Operations 

In [32]:
#Q14.1: Convert years active to months
yrs=banking_data[:,4]
months=yrs*12
months

array([72, 96, 84, 72, 36, 72, 84, 84, 24, 60])

In [34]:
#Q14.2: Calculate the average years active
yrs=banking_data[:, 4]
average=np.mean(yrs)
average

np.float64(5.7)

In [38]:
#Q14.3: Find customers who have been active for more than 5 years
banking_data[banking_data[:, 4]>5]


array([[    1, 10346,   696,    89,     6],
       [    2,  1356,   543,    67,     8],
       [    3, 53145,   685,    46,     7],
       [    4, 85774,   466,    35,     6],
       [    6, 32645,   636,    96,     6],
       [    7, 78547,   564,    57,     7],
       [    8, 64477,   553,    73,     7]])

In [41]:
#Q14.4: Calculate the total time all customers have been active (in years)
yr=banking_data[:,4]
total=np.sum(yr)
total

np.int64(57)

In [43]:
#Q14.5: Find the customer with the shortest time active
yr=banking_data[:,4]
short=np.min(yr)
short

np.int64(2)

###  Advanced Array Operations 

In [45]:
#Q15.1: Apply a function to calculate 5% interest on all account balances
bal=banking_data[:,1]
interest=bal*0.5
interest

array([ 5173. ,   678. , 26572.5, 42887. , 33932.5, 16322.5, 39273.5,
       32238.5, 13377. , 28421.5])

In [46]:
#Q15.2: Use np.where to categorize customers by balance ranges
bal=banking_data[:,1]
categories=np.where(bal<2000,'low',np.where(bal<=6000,'medium','high'))
categories

array(['high', 'low', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high'], dtype='<U6')

In [4]:
#Q15.3: Use np.select to categorize customers by credit score ranges
credit_scores = banking_data[:, 2]
conditions = [
    credit_scores < 350,
    (credit_scores >= 350) & (credit_scores < 400),
    (credit_scores >= 400) & (credit_scores < 450),
    credit_scores >= 450
]
chocies = ['poor', 'good', 'fair','Excellent']
score_categories = np.select(conditions, chocies, default='Unknown')
print(score_categories)



['Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent']


In [8]:
#Q15.4: Use np.piecewise to apply different interest rates based on balance
def low_interest(x): return x * 1.05  
def mid_interest(x): return x * 1.10  
def high_interest(x): return x * 1.20  

interest_prices = np.piecewise(
    banking_data[:, 1],
    [banking_data[:, 1] < 20000, (banking_data[:, 1] >= 20000) & (banking_data[:, 1] < 25000), banking_data[:, 1] >= 25000],
    [low_interest, mid_interest, high_interest]
)
print(interest_prices)



[ 10863   1423  63774 102928  81438  39174  94256  77372  32104  68211]


In [54]:
#Q15.5: Use np.apply_along_axis to calculate the sum of each row
import numpy as np

# Use np.apply_along_axis to calculate row sums
row_sums = np.apply_along_axis(np.sum, axis=1, arr=banking_data)

print(row_sums)

[11138  1976 53886 86285 68472 33389 79182 65118 27699 57371]


### Array Concatenation and Stacking

In [58]:
#Q16.1: Concatenate two arrays horizontally using np.hstack()
import numpy as np
a=np.array([
    [1,2],
    [3,4],
    [5,6]
])
b=np.array([
    [12,34],
    [32,23],
    [42,15]
])
result=np.hstack((a,b))
result

array([[ 1,  2, 12, 34],
       [ 3,  4, 32, 23],
       [ 5,  6, 42, 15]])

In [59]:
#Q16.2: Concatenate two arrays vertically using np.vstack()
import numpy as np
a=np.array([
    [1,2],
    [3,4],
    [5,6]
])
b=np.array([
    [12,34],
    [32,23],
    [42,15]
])
result=np.vstack((a,b))
result

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [12, 34],
       [32, 23],
       [42, 15]])

In [63]:
#Q16.3: Concatenate arrays along a specific axis using np.concatenate()
import numpy as np
a=np.array([
    [1,2],
    [3,4],
    [5,6]
])
b=np.array([
    [12,34],
    [32,23],
    [42,15]
])
result=np.concatenate((a,b),axis=1)
result

array([[ 1,  2, 12, 34],
       [ 3,  4, 32, 23],
       [ 5,  6, 42, 15]])

In [65]:
#Q16.4: Stack arrays depth-wise using np.dstack()
np.dstack((a,b))

array([[[ 1, 12],
        [ 2, 34]],

       [[ 3, 32],
        [ 4, 23]],

       [[ 5, 42],
        [ 6, 15]]])

In [66]:
#Q16.5: Create a column stack using np.column_stack()
np.column_stack((a,b))

array([[ 1,  2, 12, 34],
       [ 3,  4, 32, 23],
       [ 5,  6, 42, 15]])

### Array Splitting Operations

In [67]:
#Q17.1: Split an array into 3 equal parts using np.split()
arr=np.array([1,2,3,4,5,6,7,8,9])
np.split(arr,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [70]:
#Q17.2: Split an array at specific indices using np.split()
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.split(arr,[3,8])

[array([0, 1, 2]), array([3, 4, 5, 6, 7]), array([8, 9])]

In [73]:
#Q17.3: Split an array horizontally using np.hsplit()
arr = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9,10,11,12]
])
np.hsplit(arr,3)

[array([[1, 2],
        [7, 8]]),
 array([[ 3,  4],
        [ 9, 10]]),
 array([[ 5,  6],
        [11, 12]])]

In [77]:
#Q17.4: Split an array vertically using np.vsplit()
arr = np.array([
     [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9,10],
    [11,12]
   
])
np.vsplit(arr,3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [79]:
#Q17.5: Split an array into equal chunks using np.array_split()
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
parts = np.array_split(arr, 3)
print(part)

[ 8  9 10]


### Array Repetition and Tiling

In [80]:
# Repeat each element of an array 3 times using np.repeat()
arr=np.array([1,2,3])
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [81]:
#Q18.3: Repeat a 2D array using np.tile()
import numpy as np
arr = np.array([[1, 2],
                [3, 4]])
np.tile(arr,(2,3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [82]:
#Q18.4: Create a pattern using np.tile()
import numpy as np
np.tile([0, 1], 5)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [83]:
#Q18.5: Repeat elements with different counts using np.repeat()
import numpy as np
arr = np.array([10, 20, 30])
repeats = np.array([1, 2, 3]) 
result = np.repeat(arr, repeats)
print(result)

[10 20 20 30 30 30]


### Array Comparison and Logical Operations

In [4]:
#Q19.1: Compare two arrays for equality using np.array_equal()
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.array([2,3,4])
print(np.array_equal(a,b))
print(np.array_equal(a,c))

True
False


In [6]:
#Q19.2: Check if arrays are close using np.allclose()
import numpy as np
a=np.array([1,2,3])
b=np.array([1,9,3])
print(np.allclose(a,b))


False


In [8]:
#Q19.3: Apply logical AND operation between arrays
a=np.array([0,2,3])
b=np.array([3,2,1])
print(np.logical_and(a,b))

[False  True  True]


In [10]:
#Q19.4: Apply logical OR operation between arrays
a=np.array([1,0,0])
b=np.array([3,0,7])
print(np.logical_or(a,b))

[ True False  True]


In [11]:
#Q19.5: Apply logical NOT operation to an array
a=np.array([1,2,0])
b=np.array([2,0,3])
print(np.logical_not(a,b))

[0 0 1]


### Array Set Operations

In [12]:
#Q20.1: Find unique elements in an array using np.unique()
a=np.array([1,23,3,1,4,6,3,4,7,9,7,67,85])
print(np.unique(a))

[ 1  3  4  6  7  9 23 67 85]


In [14]:
#Q20.2: Find the intersection of two arrays using np.intersect1d()
a=np.array([1,2,3,5,7,9,])
b=np.array([1,3,45,8,0,2,5])
print(np.intersect1d(a,b))

[1 2 3 5]


In [17]:
#Q20.3: Find the union of two arrays using np.union1d()
a=np.array([1,0,2,3,5,7,9,])
b=np.array([1,3,45,8,0,2,5])
print(np.union1d(a,b))

[ 0  1  2  3  5  7  8  9 45]


In [19]:
#Q20.4: Find elements in first array but not in second using np.setdiff1d()
a=np.array([1,0,2,3,5,7,9,])
b=np.array([1,3,45,8,0,2,5])
print(np.setdiff1d(b,a))

[ 8 45]


In [22]:
#Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
a=np.array([1,0,2,3,5,7,9,])
b=np.array([1,3,45,8,0,2,5])
print(np.setxor1d(a,b))  #(a ∪ b) - (a ∩ b)

[ 7  8  9 45]


In [7]:
#interest rates based on balance
def low_interest(x): return x * 1.05  
def mid_interest(x): return x * 1.10  
def high_interest(x): return x * 1.20  

interest_prices = np.piecewise(
    banking_data[:, 1],
    [banking_data[:, 1] < 20000, (banking_data[:, 1] >= 20000) & (banking_data[:, 1] < 25000), banking_data[:, 1] >= 25000],
    [low_interest, mid_interest, high_interest]
)
print(interest_prices)

[ 10863   1423  63774 102928  81438  39174  94256  77372  32104  68211]
